
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host : localhost
  username: postgres
  password: 12345678
development:
  <<: *default
  database: fp_deck_dev
test:
  <<: *default
  database: fp_deck_test
production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  port: 5432
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
